# 1. Étape de Build (Node.js)
FROM node:20-alpine AS builder
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ .
RUN npm run build

# 2. Étape de Production (Nginx)
FROM nginx:alpine
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
# Remplacez 'dist' par 'build' si vous utilisez Create React App au lieu de Vite
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]