import os
import time
from contextlib import contextmanager
from pathlib import Path

from dotenv import load_dotenv
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

load_dotenv(Path(__file__).with_name(".env"))

DATABASE_URL = os.getenv("DATABASE_URL")

SCHEMA = (
    """CREATE TABLE IF NOT EXISTS events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        device_id TEXT NOT NULL,
        ts BIGINT NOT NULL,
        type TEXT NOT NULL,
        state TEXT NOT NULL,
        value DOUBLE PRECISION,
        unit TEXT,
        received_at BIGINT NOT NULL
    )""",
    "CREATE INDEX IF NOT EXISTS idx_events_ts ON events(ts)",
    """CREATE TABLE IF NOT EXISTS telemetry (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        device_id TEXT NOT NULL,
        ts BIGINT NOT NULL,
        temperature DOUBLE PRECISION,
        gas DOUBLE PRECISION,
        humidity DOUBLE PRECISION,
        motion SMALLINT,
        label TEXT
    )""",
    "CREATE INDEX IF NOT EXISTS idx_telemetry_ts ON telemetry(ts)",
    "ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS motion SMALLINT",
    "ALTER TABLE telemetry ADD COLUMN IF NOT EXISTS label TEXT",
    """CREATE TABLE IF NOT EXISTS commands (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        device_id TEXT NOT NULL,
        target TEXT NOT NULL,
        action TEXT NOT NULL,
        duration_ms INTEGER,
        created_at BIGINT NOT NULL,
        delivered BOOLEAN NOT NULL DEFAULT FALSE
    )""",
    """CREATE TABLE IF NOT EXISTS devices (
        device_id TEXT PRIMARY KEY,
        last_seen BIGINT NOT NULL
    )""",
)

pool: ConnectionPool | None = None


@contextmanager
def get_conn():
    if pool is None:
        raise RuntimeError("PostgreSQL connection pool has not been initialized")
    with pool.connection() as conn:
        yield conn


def init_db():
    global pool
    if pool is not None:
        return
    if not DATABASE_URL:
        raise RuntimeError("DATABASE_URL is required to connect to PostgreSQL")

    new_pool = ConnectionPool(
        conninfo=DATABASE_URL,
        min_size=1,
        max_size=10,
        kwargs={"row_factory": dict_row},
        open=False,
    )
    new_pool.open(wait=True)
    try:
        with new_pool.connection() as conn:
            for statement in SCHEMA:
                conn.execute(statement)
    except Exception:
        new_pool.close()
        raise
    pool = new_pool


def close_db():
    global pool
    if pool is not None:
        pool.close()
        pool = None


def touch_device(c, device_id: str):
    c.execute(
        "INSERT INTO devices(device_id, last_seen) VALUES(%s, %s) "
        "ON CONFLICT(device_id) DO UPDATE SET last_seen=excluded.last_seen",
        (device_id, int(time.time())),
    )